### ISSUE TITLE
How can I move the agent?

### ISSUE THREAD

**Issue by ghost** [barmayo/spatial_attention#5]
Hi, how can I move the agent around or see if the agent is moving when evaluating?

When I run evaluation, this code opens 4 unity workers, and then they stay still
![Screenshot from 2022-06-23 15-04-55](https://user-images.githubusercontent.com/17596799/175226813-eb2b32d9-0755-4f25-948b-c19633302587.png)
.

Thank you very much

**Comment by barmayo** [comment]
Hi,

Its been awhile since I run the code, so I'm not really sure about what may cause this bug. specially the 4 windows.

If I remember correctly what the code is supposed to be doing is to get the action from the model and use it to look for right image in the data set (the images are arranged by the agent's position and location). 

First, I would try to save the results of the evaluation without running unity (not viewing the path in real time) in order to verifying we actually get a policy from the model. Than I would try and recreate the tracks by finding the corresponding agent's location and position.

Also, as this simulation code is heavily based on this git: https://github.com/allenai/savn
I would look over there. Maybe someone had encounter a similar problem.

Hopes this helps,
Bar

**Comment by ghost** [comment]
So, after I train my new model, I have to find a way to recreate the path (Coz I dont know how to visualize the images on the unity) in order to generate figures similar to your paper.

**Comment by barmayo** [comment]
Hi,

As I said, in the GitHub repository of AllenAI there is a .h5py dataset file with all the images. Each labeled by agent's position and location.
If you want to recreate the trajectory figure I answered this question in this link: https://github.com/barmayo/spatial_attention/issues/1

Good luck,
Bar
